### ISSUE TITLE
static S3 연동

### ISSUE THREAD

**Issue by golony6449** [pythonkr/pyconkr-web-2022#10]
* 로컬에서는 가능
* zappa 배포 이후 S3 설정문제로 오류발생

![image](https://user-images.githubusercontent.com/10653376/155833012-19f20405-aa14-47da-89de-b08b4480df80.png)

aws credential 설정을 넘겨주던지, 환경변수로 ID, Secret을 직접 넘겨야 할듯

**Comment by darjeeling** [comment]
zappa 설정을 비밀 리포로 옴기는 걸 해보겠습니다

**Comment by golony6449** [comment]
@darjeeling 
감사합니다!
어제 변경한 사항들은 프로젝트 전체에 영향을 주는 것들이어어서 main에 바로 푸시했습니다 ㅠㅠ

오늘부터는 program쪽 작업을 할 계획이어서 main에 바로 푸시하셔도 될것 같아요!

**Comment by golony6449** [comment]
* 비밀키를 별도의 레포에서 관리하도록 개선 ([darjeeling](https://github.com/darjeeling) 님 감사합니다.)

* 로컬에서 `python manage.py collectstatic`으로 S3 버킷에 static 파일을 올릴 수 있음
