### ISSUE TITLE
Swagger 추가

### ISSUE THREAD

**Issue by golony6449** [pythonkr/pyconkr-web-2022#63]
우리 모두를 위해 Swagger를 붙혀 보겠습니다.
(우선 순위는 뒤로 미룰게요)

**Comment by darjeeling** [comment]
how about  `drf-spectacular` ?
https://velog.io/@catveloper/DRF-Spectacular-%EC%82%AC%EC%9A%A9%EB%B2%95

**Comment by golony6449** [comment]
감사합니다 :-)
